[General]
background=
basicTextColor=#ffffff
backgroundFillMode=aspect
wrongPasswordBorderRadius=0
wrongPasswordBorderColor=#ff3117
passwordTextColor=#ffffff
passwordCharacter=*
passwordInputBackground=transparent
passwordInputBorderColor=#ffffff
passwordCursorColor=#ffffff
font=monospace
helpFont=monospace
showUserRealNameByDefault=true
passwordMask=true
passwordInputCursorVisible=true
passwordAllowEmpty=false
cursorBlinkAnimation=true
showUsersByDefault=true
showSessionsByDefault=true
hideCursor=false
passwordFontSize=96
usersFontSize=48
sessionsFontSize=24
helpFontSize=18
blurRadius=0
passwordInputRadius=10
passwordInputBorderWidth=0
passwordInputWidth=0.5
